### ISSUE TITLE
Můžu to použít?

### ISSUE THREAD

**Issue by encukou** [messa/pyladies-courseware#1]
Tenhle projekt nemá licenci. Můžu si ho stáhnout/vyzkoušet/upravit?

Ve `frontend/package.json` je uvedená [ISC](https://opensource.org/licenses/ISC), která umožňuje spouštění/změny/šíření pokud k tomu vždycky přiložíš text licence – ale samotný text licence chybí :(

**Comment by encukou** [comment]
Tož dej MIT! Taky ji používám, a je natolik benevolentní že není problém ji změnit, kdyby z nějakého důvodu přestala vyhovovat :)

**Comment by messa** [comment]
Je to tam :)

https://github.com/messa/pyladies-courseware/commit/1a2caab080a02a3a01c1e827d7c0f41387a2a2ee
https://github.com/messa/pyladies-courseware/commit/c6fce85cc98a5dc9a7a0b257bd88f31ac8b5b232

**Comment by encukou** [comment]
:fireworks: Díky!
