### ISSUE TITLE
Copy to clipboard button

### ISSUE THREAD

**Issue by frenzymadness** [messa/pyladies-courseware#139]
U komplexnějších úloh potřebujeme jejich řešení spustit a ověřitm že opravdu funguje. Kopírovat si je jednu po druhé do lokálního editoru a spustit je celkem opruz. Napadají mě dvě možnosti:

* Implementovat možnost stáhnout si dosud neopravené úlohy jako .zip soubor, lokálně rozbalit a pracovat s nimi. Ideálně možnost stáhnout si všechny neopravené, všechny neopravené pro konkrétní účastnici a všechny neopravené pro konkrétní task - tedy všechny, po řádcích a po sloupcích. Je samozřejmě možné tuhle strukturu udělat i ve formě složek uvnitř zip souboru.
* Umožnit stahování řešení přes API a implementovat k tomu jednoduchého CLI klienta, který úkol stáhne, ukáže, spustí a umožní označit za vyřešený. Tohle je asi zbytečně složité, ale možnost to je.

Cc @mcurlej

**Comment by encukou** [comment]
BTW, já (na Linuxu) spouštím rychleji než kopírováním do editoru:
* v prohlížeči vybrat myší
* v terminálu výběr spustit pomocí `xsel > /tmp/foo.py; python3 /tmp/foo.py`

**Comment by frenzymadness** [comment]
To zní dobře. Třeba by šlo udělat tlačítko "copy to clipboard", které by to ještě zrychlilo.

**Comment by Disi77** [comment]
ano přidávám se "copy to clipboard" by bylo naprosto skvělé

**Comment by Mintaka** [comment]
Copy to clipboard funguje. Asi můžeme zavřít issue.
