### ISSUE TITLE
umoznit pohled na ruzne reseni jednoho ukolu

### ISSUE THREAD

**Issue by vasekch** [messa/pyladies-courseware#18]
Umoznit prochazet ukoly postupne podle cisla pro vsechny ucastnice.
Tenhle pohled by mohl slouzit taky pri demonstraci ukolu na kurzu, stacilo by schovat jmena a komentare...

**Comment by messa** [comment]
Někdo mi říkal ještě nápad, že by chtěl vidět svoje vlastní komentáře k danému úkolu, které psal i jiným studentům, protože se např. často opakuje stejná chyba.
