### ISSUE TITLE
pridat do role student priznak hidden

### ISSUE THREAD

**Issue by vasekch** [messa/pyladies-courseware#19]
Jako kouc mam problem, ze se mi v tabulce udevzdani pletou ostatni koucove.

Navrh:
 - Do role student pridat priznak hidden.
 - Pridat k tabulce odevzdani prepinacek "zobrazit schované" nebo nejaka lepsi textace, ktera me ted nenapada

**Comment by messa** [comment]
Koučové by asi neměli mít roli student. Vyřeší to #23.

**Comment by messa** [comment]
Ostatní koučové se v tabulce pletli, protože je systém zároveň zapsal jako studenty. Vysvětlení a pokračování v #46 :)
