### ISSUE TITLE
Plugin to create links from standard URLs

### ISSUE THREAD

**Issue by veronikks** [messa/pyladies-courseware#194]
See in task 4 at:
https://projekty.pyladies.cz/session?course=pydata-2020-praha-jaro&session=eda3 :) 
Thanks

**Comment by messa** [comment]
Before:

![image](https://user-images.githubusercontent.com/115487/74106729-58b30d00-4b69-11ea-962e-48e1093e6e15.png)

After:

![image](https://user-images.githubusercontent.com/115487/74106795-f0186000-4b69-11ea-88d5-de8460fe9f09.png)
