### ISSUE TITLE
umoznit administrovat kurzy

### ISSUE THREAD

**Issue by vasekch** [messa/pyladies-courseware#22]
Jako admin bych chtel mit moznost
- zalozit novy kurz
- zmenit nazev kurzu
- nastavit priznaky uzavreny, skonceny dle #21

**Comment by messa** [comment]
Tohle se týká toho, odkud se berou data o kurzech.

Buď je "zdrojem pravdy" naučse.python.cz a potom název kurzu, dobu trvání bereme odtamtud. To je v plánu, ale nejdřív je k tomu potřeba dodělat API: https://github.com/pyvec/naucse.python.cz/issues/431

Nebo je ten kurz managovaný pomocí YAML souborů v Githubu a patří to do nich: https://github.com/messa/pyladies-courseware/tree/master/courses

Podle mě je tohle vhodnější, protože lze využít už zavedené mechanismy typu Github pull request s reviews nebo deployment do testovacího prostředí, kde je možné si prohlédnout výsledek.

Ale záleží, k čemu bys to potřeboval? Jestli by se kurzy dělaly nějak ve velkém, tak by jejich administrace dávala smysl.

**Comment by messa** [comment]
Seznam, struktura a metadata kurzů jsou v YAML souborech přímo v Github repozitáři [pyladies-courseware](https://github.com/messa/pyladies-courseware/tree/master/data). Může v nich být odkaz na Naučse API, pak se struktura konkrétního kurzu (seznam hodin (_sessions_) a jejich obsah) načítá z [naucse.python.cz](https://naucse.python.cz/). Mechanismus pro aktualizaci obojího jsou Github pull requesty :)

Že je kurz uzavřený se aktuálně detekuje podle datumu poslední hodiny. Možná to není ideální, pokud by následovala nějaká aktivita i potom. Ale jediné, co je tímto zatím ovlivněno, je, zda se kurz objeví na homepage v sekci aktivních nebo již proběhlých kurzů.

Co se týče např. správy účastníků kurzu, tak to se bude řešit v #80.
