### ISSUE TITLE
zamyslet se nad autozapisovanim do kurzu po prvni navsteve

### ISSUE THREAD

**Issue by vasekch** [messa/pyladies-courseware#23]
Kdyz chodi koucove po ruznych kurzech, tak jsou zapsani jako studenti a dela to bordel. Navic nektere ucastnice to delaji taky, nektere ze zvedavosti, nektere protoze chteji odevzdat na vice mist (napr. zmenili kurz, nahrazuji si hodinu), vzdycky by asi meli odevzdavat tam, kam prijdou, at se jim k tomu muze kouc vyjadrit...

asi bych tuhle featuru obetoval a dovnitr do kurzu dal zapinac "prihlasit se jako ucastnik", odhlasit se nepujde, ale mohl by se clovek (kouc nebo ucastnice) sam schovat (viz. #19 ).

**Comment by messa** [comment]
Díky za podněty! Pokračování v #46 :)
