### ISSUE TITLE
Umožnit u odevzdaných úloh syntax highlight

### ISSUE THREAD

**Issue by NevermoreX0** [messa/pyladies-courseware#27]
Umožnit u odevzdaných úloh syntax highlight pro python.

**Comment by messa** [comment]
BTW. Koukám, že např. umimeprogramovat.cz pro zvýrazňování syntaxe používá [Prism](https://prismjs.com/) (a pro editaci používají také CodeMirror)

**Comment by Kobzol** [comment]
Někdy je odpovědí text, někdy kód, někdy kombinace obojího. Mělo by smysl označovat úkoly nějakým tagem, že se v nich očekává kód, anebo nahrubo highlightovat všechno? Popř. zapínat highlight, pokud budou detekovaná klíčová slova, nebo nějakým tlačítkem ve frontendu jako opt-in?

**Comment by Kobzol** [comment]
Implemented in https://github.com/messa/pyladies-courseware/pull/372.
