### ISSUE TITLE
CZ.NIC - domácí úkoly - 6. lekce

### ISSUE THREAD

**Issue by msvobodova** [messa/pyladies-courseware#33]
Ahoj, 

na webu naucese.python.cz zadání domácích úkolů nekoresponduje se zadáním na jednotlivé hodiny v odevzdávcím toolu. 

lekce 6 (https://naucse.python.cz/2018/pyladies-praha-podzim-cznic/) - Domácí projekty jsou jiné než zde: https://projekty.pyladies.cz/lesson?course=pyladies-2018-praha-podzim-olsanka&lesson=6-opensource-a-git

Šlo by to prosím updatovat na projekty, které jsou v naucse.python.cz? 

Díky moc
Marketa

**Comment by EliskaPy** [comment]
Ahoj,
vsimla jsem si, ze i lekce 7 je posunuta.

Zmen prosim te v odevzdavatku (O) za materialy z naucse.python (NP) toto:

O (Lekce 6) ---> NP (https://naucse.python.cz/2018/pyladies-praha-podzim-cznic/sessions/vcs/  - Domaci projekty - nelze poslat odkaz primo)

O (Lekce 7) ---> NP (https://pyladies.cz/v1/s006-lists/handout/handout6.pdf)

Dik,
Eliska

**Comment by messa** [comment]
@msvobodova @EliskaPy Zadání těchto úkolů přepisoval dobrovolník Roman na sprintu ve Mšeném. Zřejmě nastalo nedorozumění plynoucí z různého číslování názvů souborů `handoutN.pdf` a dokonce v nadpisech v nich oproti číslům lekcí. Opravím. Nejspíš můžou být mimo i následující lekce.

**Comment by messa** [comment]
@msvobodova @EliskaPy Lekce 6 a 7 opraveny
